// react-app/src/App.js
import { useState } from "react";
import "./App.css";

export default function App() {
  const [inputMessage, setInputMessage] = useState("");
  const [displayedMessage, setDisplayedMessage] = useState("Hello World");

  function displayMessage() {
    setDisplayedMessage(inputMessage);
  }

  return (
    <main className="card">
      <p className="badge">React</p>
      <h1>Message Display</h1>

      <label htmlFor="messageInput">Message to Display</label>
      <input
        id="messageInput"
        type="text"
        value={inputMessage}
        onChange={(e) => setInputMessage(e.target.value)}
        placeholder="Type a message"
      />

      <button type="button" onClick={displayMessage}>
        Display Message
      </button>

      <h2>{displayedMessage}</h2>
    </main>
  );
}

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  inputMessage = '';
  displayedMessage = 'Hello World';

  displayMessage(): void {
    this.displayedMessage = this.inputMessage;
  }
}

<main class="card">
  <p class="badge">Angular</p>
  <h1>Message Display</h1>

  <label for="messageInput">Message to Display</label>
  <input
    id="messageInput"
    type="text"
    [(ngModel)]="inputMessage"
    placeholder="Type a message"
  />

  <button type="button" (click)="displayMessage()">Display Message</button>

  <h2>{{ displayedMessage }}</h2>
</main>
